test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

minio:
  service: S3
  access_key_id: <%= ENV.fetch("ACTIVE_STORAGE_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("ACTIVE_STORAGE_SECRET_ACCESS_KEY") %>
  region: <%= ENV.fetch("ACTIVE_STORAGE_REGION", "us-east-1") %>
  bucket: <%= ENV.fetch("ACTIVE_STORAGE_BUCKET") %>
  endpoint: <%= ENV.fetch("ACTIVE_STORAGE_ENDPOINT") %>
  force_path_style: true
  ssl_verify_peer: false

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
