/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPersonnelRouteImport } from './routes/_authenticated/_personnel'
import { Route as AuthenticatedAdminRbacRouteImport } from './routes/_authenticated/admin/rbac'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedPersonnelPayRouteImport } from './routes/_authenticated/_personnel/pay'
import { Route as AuthenticatedPersonnelHelpRouteImport } from './routes/_authenticated/_personnel/help'
import { Route as AuthenticatedPersonnelDashboardRouteImport } from './routes/_authenticated/_personnel/dashboard'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminTicketsIndexRouteImport } from './routes/_authenticated/admin/tickets/index'
import { Route as AuthenticatedAdminPayrollIndexRouteImport } from './routes/_authenticated/admin/payroll/index'
import { Route as AuthenticatedPersonnelComplaintsIndexRouteImport } from './routes/_authenticated/_personnel/complaints/index'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users/$userId'
import { Route as AuthenticatedAdminTicketsTicketIdRouteImport } from './routes/_authenticated/admin/tickets/$ticketId'
import { Route as AuthenticatedAdminPayrollUploadRouteImport } from './routes/_authenticated/admin/payroll/upload'
import { Route as AuthenticatedPersonnelComplaintsNewRouteImport } from './routes/_authenticated/_personnel/complaints/new'
import { Route as AuthenticatedPersonnelComplaintsComplaintIdRouteImport } from './routes/_authenticated/_personnel/complaints/$complaintId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonnelRoute = AuthenticatedPersonnelRouteImport.update({
  id: '/_personnel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRbacRoute = AuthenticatedAdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPersonnelPayRoute =
  AuthenticatedPersonnelPayRouteImport.update({
    id: '/pay',
    path: '/pay',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelHelpRoute =
  AuthenticatedPersonnelHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelDashboardRoute =
  AuthenticatedPersonnelDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsIndexRoute =
  AuthenticatedAdminTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayrollIndexRoute =
  AuthenticatedAdminPayrollIndexRouteImport.update({
    id: '/payroll/',
    path: '/payroll/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPersonnelComplaintsIndexRoute =
  AuthenticatedPersonnelComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsTicketIdRoute =
  AuthenticatedAdminTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayrollUploadRoute =
  AuthenticatedAdminPayrollUploadRouteImport.update({
    id: '/payroll/upload',
    path: '/payroll/upload',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPersonnelComplaintsNewRoute =
  AuthenticatedPersonnelComplaintsNewRouteImport.update({
    id: '/complaints/new',
    path: '/complaints/new',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelComplaintsComplaintIdRoute =
  AuthenticatedPersonnelComplaintsComplaintIdRouteImport.update({
    id: '/complaints/$complaintId',
    path: '/complaints/$complaintId',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/dashboard': typeof AuthenticatedPersonnelDashboardRoute
  '/help': typeof AuthenticatedPersonnelHelpRoute
  '/pay': typeof AuthenticatedPersonnelPayRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/rbac': typeof AuthenticatedAdminRbacRoute
  '/complaints/$complaintId': typeof AuthenticatedPersonnelComplaintsComplaintIdRoute
  '/complaints/new': typeof AuthenticatedPersonnelComplaintsNewRoute
  '/admin/payroll/upload': typeof AuthenticatedAdminPayrollUploadRoute
  '/admin/tickets/$ticketId': typeof AuthenticatedAdminTicketsTicketIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/complaints/': typeof AuthenticatedPersonnelComplaintsIndexRoute
  '/admin/payroll/': typeof AuthenticatedAdminPayrollIndexRoute
  '/admin/tickets/': typeof AuthenticatedAdminTicketsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/dashboard': typeof AuthenticatedPersonnelDashboardRoute
  '/help': typeof AuthenticatedPersonnelHelpRoute
  '/pay': typeof AuthenticatedPersonnelPayRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/rbac': typeof AuthenticatedAdminRbacRoute
  '/complaints/$complaintId': typeof AuthenticatedPersonnelComplaintsComplaintIdRoute
  '/complaints/new': typeof AuthenticatedPersonnelComplaintsNewRoute
  '/admin/payroll/upload': typeof AuthenticatedAdminPayrollUploadRoute
  '/admin/tickets/$ticketId': typeof AuthenticatedAdminTicketsTicketIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/complaints': typeof AuthenticatedPersonnelComplaintsIndexRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollIndexRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/_personnel': typeof AuthenticatedPersonnelRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_personnel/dashboard': typeof AuthenticatedPersonnelDashboardRoute
  '/_authenticated/_personnel/help': typeof AuthenticatedPersonnelHelpRoute
  '/_authenticated/_personnel/pay': typeof AuthenticatedPersonnelPayRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/rbac': typeof AuthenticatedAdminRbacRoute
  '/_authenticated/_personnel/complaints/$complaintId': typeof AuthenticatedPersonnelComplaintsComplaintIdRoute
  '/_authenticated/_personnel/complaints/new': typeof AuthenticatedPersonnelComplaintsNewRoute
  '/_authenticated/admin/payroll/upload': typeof AuthenticatedAdminPayrollUploadRoute
  '/_authenticated/admin/tickets/$ticketId': typeof AuthenticatedAdminTicketsTicketIdRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/_personnel/complaints/': typeof AuthenticatedPersonnelComplaintsIndexRoute
  '/_authenticated/admin/payroll/': typeof AuthenticatedAdminPayrollIndexRoute
  '/_authenticated/admin/tickets/': typeof AuthenticatedAdminTicketsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboard'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/profile'
    | '/dashboard'
    | '/help'
    | '/pay'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/rbac'
    | '/complaints/$complaintId'
    | '/complaints/new'
    | '/admin/payroll/upload'
    | '/admin/tickets/$ticketId'
    | '/admin/users/$userId'
    | '/complaints/'
    | '/admin/payroll/'
    | '/admin/tickets/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboard'
    | '/reset-password'
    | '/setup'
    | '/'
    | '/admin'
    | '/profile'
    | '/dashboard'
    | '/help'
    | '/pay'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/rbac'
    | '/complaints/$complaintId'
    | '/complaints/new'
    | '/admin/payroll/upload'
    | '/admin/tickets/$ticketId'
    | '/admin/users/$userId'
    | '/complaints'
    | '/admin/payroll'
    | '/admin/tickets'
    | '/admin/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/onboard'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/_personnel'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/_personnel/dashboard'
    | '/_authenticated/_personnel/help'
    | '/_authenticated/_personnel/pay'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/rbac'
    | '/_authenticated/_personnel/complaints/$complaintId'
    | '/_authenticated/_personnel/complaints/new'
    | '/_authenticated/admin/payroll/upload'
    | '/_authenticated/admin/tickets/$ticketId'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/_personnel/complaints/'
    | '/_authenticated/admin/payroll/'
    | '/_authenticated/admin/tickets/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_personnel': {
      id: '/_authenticated/_personnel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPersonnelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rbac': {
      id: '/_authenticated/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AuthenticatedAdminRbacRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_personnel/pay': {
      id: '/_authenticated/_personnel/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof AuthenticatedPersonnelPayRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/_personnel/help': {
      id: '/_authenticated/_personnel/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedPersonnelHelpRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/_personnel/dashboard': {
      id: '/_authenticated/_personnel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedPersonnelDashboardRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets/': {
      id: '/_authenticated/admin/tickets/'
      path: '/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AuthenticatedAdminTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payroll/': {
      id: '/_authenticated/admin/payroll/'
      path: '/payroll'
      fullPath: '/admin/payroll/'
      preLoaderRoute: typeof AuthenticatedAdminPayrollIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_personnel/complaints/': {
      id: '/_authenticated/_personnel/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthenticatedPersonnelComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets/$ticketId': {
      id: '/_authenticated/admin/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedAdminTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payroll/upload': {
      id: '/_authenticated/admin/payroll/upload'
      path: '/payroll/upload'
      fullPath: '/admin/payroll/upload'
      preLoaderRoute: typeof AuthenticatedAdminPayrollUploadRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_personnel/complaints/new': {
      id: '/_authenticated/_personnel/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AuthenticatedPersonnelComplaintsNewRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/_personnel/complaints/$complaintId': {
      id: '/_authenticated/_personnel/complaints/$complaintId'
      path: '/complaints/$complaintId'
      fullPath: '/complaints/$complaintId'
      preLoaderRoute: typeof AuthenticatedPersonnelComplaintsComplaintIdRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
  }
}

interface AuthenticatedPersonnelRouteChildren {
  AuthenticatedPersonnelDashboardRoute: typeof AuthenticatedPersonnelDashboardRoute
  AuthenticatedPersonnelHelpRoute: typeof AuthenticatedPersonnelHelpRoute
  AuthenticatedPersonnelPayRoute: typeof AuthenticatedPersonnelPayRoute
  AuthenticatedPersonnelComplaintsComplaintIdRoute: typeof AuthenticatedPersonnelComplaintsComplaintIdRoute
  AuthenticatedPersonnelComplaintsNewRoute: typeof AuthenticatedPersonnelComplaintsNewRoute
  AuthenticatedPersonnelComplaintsIndexRoute: typeof AuthenticatedPersonnelComplaintsIndexRoute
}

const AuthenticatedPersonnelRouteChildren: AuthenticatedPersonnelRouteChildren =
  {
    AuthenticatedPersonnelDashboardRoute: AuthenticatedPersonnelDashboardRoute,
    AuthenticatedPersonnelHelpRoute: AuthenticatedPersonnelHelpRoute,
    AuthenticatedPersonnelPayRoute: AuthenticatedPersonnelPayRoute,
    AuthenticatedPersonnelComplaintsComplaintIdRoute:
      AuthenticatedPersonnelComplaintsComplaintIdRoute,
    AuthenticatedPersonnelComplaintsNewRoute:
      AuthenticatedPersonnelComplaintsNewRoute,
    AuthenticatedPersonnelComplaintsIndexRoute:
      AuthenticatedPersonnelComplaintsIndexRoute,
  }

const AuthenticatedPersonnelRouteWithChildren =
  AuthenticatedPersonnelRoute._addFileChildren(
    AuthenticatedPersonnelRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminRbacRoute: typeof AuthenticatedAdminRbacRoute
  AuthenticatedAdminPayrollUploadRoute: typeof AuthenticatedAdminPayrollUploadRoute
  AuthenticatedAdminTicketsTicketIdRoute: typeof AuthenticatedAdminTicketsTicketIdRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminPayrollIndexRoute: typeof AuthenticatedAdminPayrollIndexRoute
  AuthenticatedAdminTicketsIndexRoute: typeof AuthenticatedAdminTicketsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminRbacRoute: AuthenticatedAdminRbacRoute,
  AuthenticatedAdminPayrollUploadRoute: AuthenticatedAdminPayrollUploadRoute,
  AuthenticatedAdminTicketsTicketIdRoute:
    AuthenticatedAdminTicketsTicketIdRoute,
  AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  AuthenticatedAdminPayrollIndexRoute: AuthenticatedAdminPayrollIndexRoute,
  AuthenticatedAdminTicketsIndexRoute: AuthenticatedAdminTicketsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPersonnelRoute: typeof AuthenticatedPersonnelRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPersonnelRoute: AuthenticatedPersonnelRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
